### ISSUE TITLE
The results I obtained differ from those reported in the article.

### ISSUE THREAD

**Issue by luojing1030** [JinhaoLee/WCA#1]
Thank you for your outstanding work. After running your released code (with default parameter settings), I found significant discrepancies between my results and those reported in the paper. I tried several different random seeds, but the discrepancies persisted. For instance, for the ViT/B-32 model on the ImageNet dataset, the accuracies for different methods are as follows: {'clip': 60.83, 'clip-e': 62.20, 'clip-d': 61.88, 'waffe': 61.95, 'cupl': 63.25, 'ours': 61.21}. I'm unsure whether the issue lies with the code or my execution.

**Comment by JinhaoLee** [comment]
Thank you for reporting this issue. We have identified the problem: the number of crops was inadvertently hardcoded to 5, but it should be obtained from the config file. Please check my recent commit 233f4de11423cfcbc332e5c7d6dd4d9db27f103e for the fix.
